Widget para renderizar e imprimir componentes utilizando a impressora da POS
gabuldev/pagseguro_smart_flutter pull request #18
Opened 2024-11-06 02:18 UTC by fogaiht

Neste pull request foi criado um widget auxiliar para renderização e impressão de um widget específico utilizando a função PrintRenderWidget.print

2024-12-02 11:43 UTC, jhonathanqz commented
@fogaiht  Você chegou fazer algum teste com algum terminal? Consegue mandar uma foto de como saiu a impressão utilizando esse método?

2024-12-03 01:02 UTC, gabuldev approved these changes

2024-12-03 14:53 UTC, jhonathanqz requested changes
@fogaiht suba a versão no pubspec para 1.2.0 e adicione ao changelog por favor.

@gabuldev

2024-12-05 01:05 UTC, fogaiht commented
> @fogaiht Você chegou fazer algum teste com algum terminal? Consegue mandar uma foto de como saiu a impressão utilizando esse método?

sim, eu tenho um terminal para testes. Segue a foto da impressao

![impressao pagseguro smart](https://github.com/user-attachments/assets/e7cd3a43-eefc-400c-9587-3817f0d84716)

2024-12-05 01:09 UTC, fogaiht commented
> @fogaiht suba a versão no pubspec para 1.2.0 e adicione ao changelog por favor.
> 
> @gabuldev

ajustes feitos! 😁😁

2024-12-05 12:25 UTC, jhonathanqz approved these changes

2024-12-05 12:25 UTC, merged